// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATB1j_q3a4b2SPapzNWW2ibrJ-XIgPAYE',
    appId: '1:1083638253806:web:3bb8d2def1799424920bff',
    messagingSenderId: '1083638253806',
    projectId: 'buddy-chat-7de08',
    authDomain: 'buddy-chat-7de08.firebaseapp.com',
    storageBucket: 'buddy-chat-7de08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHRlXiySTXepQPxm6Fp4WSzaq4KK-huo',
    appId: '1:1083638253806:android:167f494b6d2bb910920bff',
    messagingSenderId: '1083638253806',
    projectId: 'buddy-chat-7de08',
    storageBucket: 'buddy-chat-7de08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRAE5awuc6JOwGg314_QhDDS5LwCsOaPc',
    appId: '1:1083638253806:ios:41f4b8517816140b920bff',
    messagingSenderId: '1083638253806',
    projectId: 'buddy-chat-7de08',
    storageBucket: 'buddy-chat-7de08.firebasestorage.app',
    androidClientId: '1083638253806-q1uq6uo7l1l86g9c22p7mqqb9tv0s6im.apps.googleusercontent.com',
    iosClientId: '1083638253806-0u93n3hnrqblfg6447klhnb59rn7kdtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATB1j_q3a4b2SPapzNWW2ibrJ-XIgPAYE',
    appId: '1:1083638253806:web:019f966b16b2072a920bff',
    messagingSenderId: '1083638253806',
    projectId: 'buddy-chat-7de08',
    authDomain: 'buddy-chat-7de08.firebaseapp.com',
    storageBucket: 'buddy-chat-7de08.firebasestorage.app',
  );

}